---
- name: Enable features
  ansible.builtin.include_tasks:
    file: enable.yml
  when: features_enabled is defined

- name: Disable features
  ansible.builtin.include_tasks:
    file: disable.yml
  when: features_disabled is defined
