---
- name: Ensure latest Powershell is installed
  chocolatey.chocolatey.win_chocolatey:
    name: powershell
    state: latest
  register: __powershell_install

- name: Reboot if needed
  ansible.windows.win_reboot:
    msg: "Ansible initiated reboot"
  when: __powershell_install.changed

- name: Ensure PowerShellGet is latest
  community.windows.win_psmodule:
    name: PowerShellGet
    state: latest

- name: Ensure Powershell modules are present
  community.windows.win_psmodule:
    name: "{{ item }}"
    state: present
  loop: "{{ __sqlserver_required_psmodules }}"
  tags:
    - prereqs

- name: Ensure Windows Features are present
  ansible.windows.win_feature:
    name: "{{ item }}"
    state: present
    include_sub_features: true
  loop: "{{ __sqlserver_required_features }}"
  tags:
    - prereqs

- name: Reboot if needed
  ansible.windows.win_reboot:
    msg: "Ansible initiated reboot"
  when: ansible_reboot_pending
  tags:
    - prereqs

- name: Ensure Download destination exists
  ansible.windows.win_file:
    path: "{{ sqlserver_download_path }}"
    state: directory

- name: Download SQL Server installer
  ansible.windows.win_get_url:
    url: "{{ sqlserver_installer_url }}"
    dest: "{{ sqlserver_download_path }}\\SQLServer-Install.exe"
  tags:
    - install

- name: Fetch installation CABs
  ansible.windows.win_shell: "{{ sqlserver_download_path }}\\SQLServer-Install.exe /Action=Download /MediaPath={{ sqlserver_install_path }} /MediaType=CAB /Quiet"
  tags:
    - install
    
- name: Ensure extraction location is empty
  ansible.windows.win_file:
    path: "{{ sqlserver_install_path }}\\Media"
    state: absent
  tags:
    - install

- name: Extract install media
  ansible.windows.win_shell: "{{ sqlserver_install_path }}\\SQLServer2019-DEV-x64-ENU.exe /X:{{ sqlserver_install_path }}\\Media /Q"

- name: Ensure SQL Server is installed
  ansible.windows.win_dsc:
    resource_name: SQLSetup
    Action: Install
    UpdateEnabled: true
    SourcePath: "{{ sqlserver_install_path }}\\Media"
    InstanceName: "{{ sqlserver_instance_name }}"
  register: __sql_server_install
  tags:
    - install