---
# Default installer is SQL Server 2019 Developer edition
sqlserver_installer_url: "https://go.microsoft.com/fwlink/p/?linkid=866662"

# Path to download setup files to
sqlserver_download_path: "C:\tmp"

# SQL Server instance configuration
sqlserver_instance_name: SQLDefaultInstance
sqlserver_drive: C
sqlserver_port: 1433