---
- name: Ensure packages are present
  hosts: all
  become: true
  gather_facts: true

  pre_tasks:
    - name: Sanitize package input
      ansible.builtin.set_fact:
        __package_list: "{{ packages_present.split('\n') }}"

    - name: Construct list of dictionaries
      ansible.builtin.set_fact:
        packages_chocolatey: "{{ {'name': __pkg} | combine({'state': 'present'}) }}"
      loop: "{{ __package_list }}"
      loop_control:
        loop_var: __pkg

  roles:
    - name: packages
