---
- name: Manage Windows Features
  hosts: all
  become: true

  roles:
    - role: features
      vars:
        features_enabled: "{{ win_features_enabled }}"
        features_disabled: "{{ win_features_disabled }}"
