---
- name: Setup Microsoft SQL Server
  hosts: "{{ s_hosts | default('all') }}"
  become: true
  
  tasks:
    - name: Run Linux setup
      ansible.builtin.include_role:
        name: microsoft.sql.server
      vars:
        mssql_accept_microsoft_odbc_driver_17_for_sql_server_eula: true
        mssql_accept_microsoft_cli_utilities_for_sql_server_eula: true
        mssql_accept_microsoft_sql_server_standard_eula: true
        mssql_password: "{{ microsoft_sql_server_password }}"
        mssql_edition: Evaluation
        mssql_version: "{{ microsoft_sql_server_version }}"
      when: ansible_os_family == 'RedHat'

    - name: Run Windows setup
      ansible.builtin.include_role:
        name: sqlserver
